architect: true
watch-files: true
max-chat-history-tokens: '8192'
restore-chat-history: false
read:
  - .github/instructions/base.instructions.md
  - README.md
  - docs/ai/index.md
  - docs/ai/core.md
  - docs/ai/modules.md
  - docs/ai/routes.md
  - docs/ai/module.paceNote.md
  - docs/ai/module.policyFoo.md
  - docs/ai/module.policyFoo.doadFoo.md
  - docs/ai/module.policyFoo.leaveFoo.md
  - docs/ai/testing.md

auto-commits: false
attribute-commit-message-author: true

map-tokens: '2048'
map-refresh: always

editor: neovim
