/**
 * src/env.d.ts
 *
 * Type definitions for environment secrets
 * These are not auto-generated by wrangler types and must be manually defined
 * Extends the auto-generated Env interface from worker-configuration.d.ts
 *
 * Top-level declarations:
 * - Env (line 13): Extends Env in cloudflare:workers module with secrets
 * - Env (line 19): Global Env extension with secrets
 */

declare module "cloudflare:workers" {
  interface Env extends CloudflareBindings {
    OPENROUTER_TOKEN: string;
    RESEND_API_KEY: string;
    RESEND_WEBHOOK_SECRET: string;
    AUTHORIZED_SENDERS: string;
    CF_AIG_AUTH: string;
    HYPERDRIVE: Hyperdrive;
    AI: Ai;
  }
}

declare global {
  interface Env extends CloudflareBindings {
    OPENROUTER_TOKEN: string;
    RESEND_API_KEY: string;
    RESEND_WEBHOOK_SECRET: string;
    AUTHORIZED_SENDERS: string;
    CF_AIG_AUTH: string;
    HYPERDRIVE: Hyperdrive;
    AI: Ai;
  }
}

export {};
