/**
 * src/env.d.ts
 *
 * Type definitions for environment secrets not generated by wrangler types.
 * Extends the auto-generated bindings from worker-configuration.d.ts.
 *
 * Top-level declarations:
 * - Env: Extends Env in cloudflare:workers module with manually typed secrets
 */

declare module "cloudflare:workers" {
  interface Env extends CloudflareBindings {
    AUTHORIZED_SENDERS: string;
    CF_AIG_AUTH: string;
    EMAIL_SECRET: string;
  }
}

declare global {
  namespace Cloudflare {
    interface Env {
      AUTHORIZED_SENDERS: string;
      CF_AIG_AUTH: string;
      EMAIL_SECRET: string;
    }
  }

  interface Env extends CloudflareBindings {
    AUTHORIZED_SENDERS: string;
    CF_AIG_AUTH: string;
    EMAIL_SECRET: string;
  }
}

export {};
